spring:
    datasource:
        url: jdbc:h2:mem:market;DB_CLOSE_DELAY=-1
        name:
        username: market
        password:
    h2:
        console:
            enabled: true
    jpa:
        database: H2
        show_sql: true